### ISSUE TITLE
youtube option don't work

### ISSUE THREAD

**Issue by ezemania2** [DorielRivalet/MHFZ_Overlay#25]
![image](https://user-images.githubusercontent.com/81659486/200343903-fc1a191b-e528-47c6-b579-9c02242315c0.png)

**Comment by DorielRivalet** [comment]
Are you using the latest version of the program? [v0.15.0](https://github.com/DorielRivalet/MHFZ_Overlay/releases/latest/download/Releases.7z)

**Comment by ezemania2** [comment]
I was with the lasted I'm downloading the new update
